import { createElement } from 'lwc';
import BST_AccountContactPicker_Cmp from 'c/bST_AccountContactPicker_Cmp';

describe('c-b-s-t-account-contact-picker-cmp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-b-s-t-account-contact-picker-cmp', {
            is: BST_AccountContactPicker_Cmp
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});